### ISSUE TITLE
 maxval calculation

### ISSUE THREAD

**Issue by djrtwo** [sigp/serialization_sandbox#1]
Awesome work! 

A few notes/questions:

### aggregate sig size
looks like  maxval for `Attestation.aggregate_sig` is off. This value will always be an array of two `uint256` values. The size of the array does not scale with the cycle length as I think it was assumed here https://github.com/sigp/serialization_sandbox/blob/master/pbuf/info.py#L174

### other array fills
These don't actually matter that much as long as we are testing the same max array fill for each serialization protocol. 

* 1000 for validators in crystallized state seems low. Estimates are on the order of at least ~100k active. https://github.com/sigp/serialization_sandbox/blob/master/pbuf/info.py#L354

* `CrystallizedState.indices_for_heights` is always `CYCLE_LENGTH*2` length rather than then 1000 in the max simulation here https://github.com/sigp/serialization_sandbox/blob/master/pbuf/info.py#L364

* Where are you getting 2000 from for max attestations in a block? https://github.com/sigp/serialization_sandbox/blob/master/pbuf/info.py#L188

* Where are you getting 1000 for max size of a committee? https://github.com/sigp/serialization_sandbox/blob/master/pbuf/info.py#L202
This would be a function of the number of active validators, the cycle length, and the number of shards and would be an output from `get_new_shuffling`.

**Comment by djrtwo** [comment]
I would also add a bunch of vars like `helpers.MAX_VALIDATORS` to be clearer to third parties and to make changing these assumed values easier

**Comment by NatoliChris** [comment]
Thanks @djrtwo 

I appreciate the help with sanity checking! 

*Aggregate_sig size* - oops! That was a silly mistake. (Why would an aggregate signature grow... duh!) 

**Other Array Fills** 

*(Note: most of this was just me experimenting through until I could source the evidence for exact numbers, I honestly appreciate the help here! :smile:  )*

I'll definitely update to match your estimates. 

As for the ``helpers.MAX_VALIDATORS`` that's a good suggestion! Thanks! :+1:

**Comment by NatoliChris** [comment]
Updated with ``helpers.PLACEHOLDER`` for those numbers to be addressed; 

Added `TODO` comments above any numbers that require finalising. 

Thanks @djrtwo! :smile:
